name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: v1.0.4

      - name: Run Tests
        run: deno test --unstable **/*.spec.ts
